# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\programming\lab02

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\programming\lab02

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	C:\msys64\mingw64\bin\ctest.exe --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\programming\lab02\CMakeFiles C:\programming\lab02\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\programming\lab02\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab02

# Build rule for target.
lab02: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lab02
.PHONY : lab02

# fast build rule for target.
lab02/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02.dir\build.make CMakeFiles/lab02.dir/build
.PHONY : lab02/fast

#=============================================================================
# Target rules for targets named lab02_cli

# Build rule for target.
lab02_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lab02_cli
.PHONY : lab02_cli

# fast build rule for target.
lab02_cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_cli.dir\build.make CMakeFiles/lab02_cli.dir/build
.PHONY : lab02_cli/fast

#=============================================================================
# Target rules for targets named lab02_tests

# Build rule for target.
lab02_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lab02_tests
.PHONY : lab02_tests

# fast build rule for target.
lab02_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_tests.dir\build.make CMakeFiles/lab02_tests.dir/build
.PHONY : lab02_tests/fast

functions.obj: functions.cpp.obj
.PHONY : functions.obj

# target to build an object file
functions.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02.dir\build.make CMakeFiles/lab02.dir/functions.cpp.obj
.PHONY : functions.cpp.obj

functions.i: functions.cpp.i
.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02.dir\build.make CMakeFiles/lab02.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s
.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02.dir\build.make CMakeFiles/lab02.dir/functions.cpp.s
.PHONY : functions.cpp.s

gtests/tests.obj: gtests/tests.cpp.obj
.PHONY : gtests/tests.obj

# target to build an object file
gtests/tests.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_tests.dir\build.make CMakeFiles/lab02_tests.dir/gtests/tests.cpp.obj
.PHONY : gtests/tests.cpp.obj

gtests/tests.i: gtests/tests.cpp.i
.PHONY : gtests/tests.i

# target to preprocess a source file
gtests/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_tests.dir\build.make CMakeFiles/lab02_tests.dir/gtests/tests.cpp.i
.PHONY : gtests/tests.cpp.i

gtests/tests.s: gtests/tests.cpp.s
.PHONY : gtests/tests.s

# target to generate assembly for a file
gtests/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_tests.dir\build.make CMakeFiles/lab02_tests.dir/gtests/tests.cpp.s
.PHONY : gtests/tests.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_cli.dir\build.make CMakeFiles/lab02_cli.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_cli.dir\build.make CMakeFiles/lab02_cli.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lab02_cli.dir\build.make CMakeFiles/lab02_cli.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... test
	@echo ... lab02
	@echo ... lab02_cli
	@echo ... lab02_tests
	@echo ... functions.obj
	@echo ... functions.i
	@echo ... functions.s
	@echo ... gtests/tests.obj
	@echo ... gtests/tests.i
	@echo ... gtests/tests.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

